### ISSUE TITLE
Fewer buttons on candidate pages

### ISSUE THREAD

**Issue by zarino** [DemocracyClub/YourNextMP-Read#106]
Buttons attract attention, yes.

But when _everything_ is a button, nothing stands out.

The sidebar of the candidate page is pretty confusing. The high contrast and sharp edges make it hard to scan the list of links, and the centre alignment means your eye has to dart around working out where to start reading.

![screen shot 2015-04-29 at 17 33 08](https://cloud.githubusercontent.com/assets/739624/7396040/e43e2408-ee95-11e4-9338-b8939fe9ad36.png)

Why not re-use the same styling as you already have on the constituency page?

![screen shot 2015-04-29 at 17 35 16](https://cloud.githubusercontent.com/assets/739624/7396073/2338ad9a-ee96-11e4-86ae-24ce68e181af.png)

**Comment by tfgg** [comment]
![image](https://cloud.githubusercontent.com/assets/103349/7432681/0def2d28-f022-11e4-965f-1cd338422f9d.png)
howzat?

**Comment by zarino** [comment]
Ahh look at that beautiful beautiful sidebar.

I wonder whether left-aligning the party logo might help too? Since now it feels a bit out on a limb being the only centred item in that area.

**Comment by tfgg** [comment]
![image](https://cloud.githubusercontent.com/assets/103349/7432773/f24c80a6-f022-11e4-833d-81abaacec99a.png)

**Comment by zarino** [comment]
Not bad!

Or you could move the party logo into the header, as I did quickly in a mockup yesterday…

![screen_shot_2015-04-30_at_15 05 31](https://cloud.githubusercontent.com/assets/739624/7432781/10aa1900-f023-11e4-977d-a4873f3a0f7f.png)

**Comment by zarino** [comment]
TBH I think left-aligned in the sidebar is pretty good.

**Comment by tfgg** [comment]
Ah yes. Yeah, I think they could be moved out. I'll work on that in a separate PR?

I wonder if there's anything clever we could do with the logos - they're all b&w, make the logo white and make the background transparent?

**Comment by zarino** [comment]
> I wonder if there's anything clever we could do with the logos - they're all b&w, make the logo white and make the background transparent?

Well you can't do that in CSS (not cross-browser, anyway) but you could process the images server-side somehow. Maybe one optimisation too far?
