### ISSUE TITLE
Markup error

### ISSUE THREAD

**Issue by winghouchan** [DemocracyClub/YourNextMP-Read#112]
Howdy!

There is an error in the markup for https://yournextmp.com/

The `head` has been opened twice and closed twice. Also there are two `title` tags.

See the image attached for the code and the pinpointed errors.

![screen-shot-2015-05-01-at-13 31 05](https://cloud.githubusercontent.com/assets/6061021/7430172/d14cba54-f006-11e4-8310-70b126608d7e.jpg)

First reported here: https://github.com/mysociety/yournextmp-popit/issues/362#issuecomment-98142479

**Comment by andylolz** [comment]
Thanks for reporting, @winghouchan. Should be fixed now
![screen shot 2015-05-01 at 20 21 22](https://cloud.githubusercontent.com/assets/464193/7435878/b85a95dc-f03f-11e4-8e9d-f3c5bc224db7.png)

**Comment by winghouchan** [comment]
No probs @andylolz :+1:
