### ISSUE TITLE
Integrate polling station data in some way.

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/YourNextMP-Read#131]
People visiting the site will benefit could be told about a few things:
1. They don't need their ~~ballot paper~~ polling card to vote [tfgg edited]
2. They can call the council if they don't have their ~~ballot paper~~ polling card any more
3. We might know (in >15% of the cases) where they should vote
4. ...etc

Adding this info to YNMP-Read would be helpful, I think.

**Comment by tfgg** [comment]
Spec from Sym:

"Polling stations: Worst case just an obvious message saying
1. You don't need a poll card to vote
2. Here's a link to a site that will help you figure out where to vote, if you don't already know
3. Don't forget to vote?  Between 7 and 10?  Or something?"

**Comment by tfgg** [comment]
Done in #138
