### ISSUE TITLE
I want to add count of past events to Meet section.

### ISSUE THREAD

**Issue by jarofgreen** [DemocracyClub/YourNextMP-Read#22]
This is because due to the curve of when events actually happen, most events happen this week or next. By the time we get to the point of the last week before the vote, which is probably when YNMP will be bussyiest, most events will have past.

Therefore I want to add past count as "social proof" that the site was useful and has now passed, and to create a sense or urgency around any remaning events.  I definetly don't want it to say "no events yet" as that implies there never were any, and gives it a slight air of failure.

> I don't think the count of past events adds any value here, as the site is about finding information that's useful to the person looking at it going forwards.

I think this will reinforce the idea tha Meet is a good site, and help drive ppl to take events there more seriously or if there are no events, it will both help them think it wasn't a failure and push them to look up events.

> I'm more in favour of a stronger call to action to add new events, maybe linking to the tweet candidate page?

This would be of interest to, but I see this as a seperate issue. (Also, I wouldn't want to push this to much because as we approach the last week there just won't be many events. So you can put a strong call to action out, "are there any events you can tell us about", the answer will be "no" and the call will be wasted. )

Anyway, I would like to add past count to this section; I think this is the right thing to do given Meet's different profile to every other DC site in that our information gets less useful as election approaches instead of more useful. I've already done the work to make data availible from Meet, happy to do a pull request on this is ppl are happy with this.

**Comment by symroe** [comment]
This was implemented in #23
