### ISSUE TITLE
Do we need 2010 people?

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/YourNextMP-Read#3]
Sorry, more of a question for @tfgg.

At the moment we have json files in the people directory that were only standing in 2010.  I don't think we needed these people for this version of the site.

**Comment by tfgg** [comment]
It does seem confusing to have 2010 candidate data hanging around and then being used to generate pages. If they get indexed by Google that could confuse voters. Let's drop candidates without 2015 candidacies.

**Comment by andylolz** [comment]
+1 to dropping them.
