### ISSUE TITLE
header layout is a bit wrong

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/YourNextMP-Read#36]
The vertical positioning of the person's picture and name seems to be a bit wrong in YNMP-read when compared to @zarino's design:

![YNMP-read vs edit.yournextmp.com](http://sphinx.mythic-beasts.com/~mark/people-page-differences.png)

**Comment by zarino** [comment]
On yournextmp.com, `h1` get a larger font-size (`2.75rem`) on large screens (`min-width: 40.063em`). I think this is part of the Foundation styles. And I worked out the height of the image to match that larger font-size, so you can either keep the small font and make the image smaller to match, or make the font bigger as Foundation does.

Also looks like a `margin-top` has crept into the `h1` – again, something that Foundation resets by default.
