### ISSUE TITLE
Link to content within the page

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/YourNextMP-Read#59]
From @frabcus:

> Constituency page: Feel like the other data (leaflets, hustings etc.)  is below the fold. Not sure that matters - will be interesting to see if people scroll and realise it is there.

Adding links to the sections in the header might help this:

![screen_shot_2015-04-22_at_09_37_12](https://cloud.githubusercontent.com/assets/242329/7270390/c99fa382-e8d3-11e4-80e6-21340e489405.png)

This would also allow us to convert the site in to a single column if we wanted to – making everything feel more spacious.

**Comment by tfgg** [comment]
Done in #64
