### ISSUE TITLE
Work out deployment

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/YourNextMP-Read#6]
[x] Nginx to serve slugs nicely
[ ] Rebuild every `n` hours (3)
[ ] Cache images locally? (from YNMP, CVs, EL, etc)

**Comment by symroe** [comment]
Deployed to http://ynmp.democracyclub.org.uk/

**Comment by tfgg** [comment]
This has been done now. Rebuilding every 15 mins, images not cached.
