### ISSUE TITLE
Make candidate name links consistent

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/YourNextMP-Read#60]
From @frabcus

> Constituency page: CVs and leaflets aren’t obviously links. They’re inconsistent about how show candidate names below - and the links for CVs candidate names go to their YNMP page not the CVs.

![screen shot 2015-04-28 at 17 03 22](https://cloud.githubusercontent.com/assets/739624/7374150/82c1f10a-edc8-11e4-92ad-ff4a6a8d0343.png)

**Comment by zarino** [comment]
I've started this in branch [issues/60-candidate-name-consistency](https://github.com/DemocracyClub/YourNextMP-Read/compare/issues/60-candidate-name-consistency?expand=1)

**Comment by tfgg** [comment]
Zarino did this in #104
