### ISSUE TITLE
image request that 404s on constituency pages

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/YourNextMP-Read#63]
I can't quite see where this request is coming from, but when I load a constituency pages [like this](https://yournextmp.com/constituency/65808/dulwich-and-west-norwood/) there's a request made for https://yournextmp.com/css/img/icon-candidates.gif which is 404.

**Comment by andylolz** [comment]
If you reinstate this image, it appears behind the first candidate e.g.:
![screen shot 2015-04-27 at 10 05 02](https://cloud.githubusercontent.com/assets/464193/7344611/f5f8d8be-ecc4-11e4-99c9-2f6f142d3def.png)
So I guess it should be removed from the css.
